const phrases=[{hanzi:"\u65e9\u5b89",pinyin:"z\u01ceo \u0101n",meaning:"Good morning.",note:"A warm everyday greeting.",category:"home"},{hanzi:"\u4f60\u4eca\u5929\u904e\u5f97\u600e\u9ebc\u6a23\uff1f",pinyin:"n\u01d0 j\u012bn ti\u0101n gu\u00f2 de z\u011bn me y\u00e0ng?",meaning:"How was your day today?",note:"Useful for checking in after work or class.",category:"home"},{hanzi:"\u6211\u6709\u9ede\u7d2f",pinyin:"w\u01d2 y\u01d2u di\u01cen l\u00e8i",meaning:"I am a little tired.",note:"A natural way to soften how you feel.",category:"home"},{hanzi:"\u53ef\u4ee5\u5e6b\u6211\u4e00\u4e0b\u55ce\uff1f",pinyin:"k\u011b y\u01d0 b\u0101ng w\u01d2 y\u012b xi\u00e0 ma?",meaning:"Could you help me for a moment?",note:"Polite and common for small favors.",category:"home"},{hanzi:"\u6211\u60f3\u559d\u6c34",pinyin:"w\u01d2 xi\u01ceng h\u0113 shu\u01d0",meaning:"I want to drink water.",note:"Swap \u6c34 for tea, coffee, or juice.",category:"food"},{hanzi:"\u9019\u500b\u5f88\u597d\u5403",pinyin:"zh\u00e8 ge h\u011bn h\u01ceo ch\u012b",meaning:"This is delicious.",note:"A happy phrase for meals and snacks.",category:"food"},{hanzi:"\u4f60\u60f3\u5403\u4ec0\u9ebc\uff1f",pinyin:"n\u01d0 xi\u01ceng ch\u012b sh\u00e9n me?",meaning:"What do you want to eat?",note:"The most important daily planning question.",category:"food"},{hanzi:"\u6211\u7b49\u4e00\u4e0b\u56de\u4f86",pinyin:"w\u01d2 d\u011bng y\u012b xi\u00e0 hu\u00ed l\u00e1i",meaning:"I will come back in a bit.",note:"Casual and useful when stepping away.",category:"plans"},{hanzi:"\u6211\u5011\u665a\u4e00\u9ede\u898b",pinyin:"w\u01d2 men w\u01cen y\u012b di\u01cen ji\u00e0n",meaning:"We will meet a little later.",note:"Good for flexible plans.",category:"plans"},{hanzi:"\u660e\u5929\u6709\u7a7a\u55ce\uff1f",pinyin:"m\u00edng ti\u0101n y\u01d2u k\u00f2ng ma?",meaning:"Are you free tomorrow?",note:"A simple way to make plans.",category:"plans"},{hanzi:"\u6211\u5f88\u60f3\u4f60",pinyin:"w\u01d2 h\u011bn xi\u01ceng n\u01d0",meaning:"I miss you a lot.",note:"Sweet, direct, and easy to remember.",category:"home"},{hanzi:"\u8f9b\u82e6\u4e86",pinyin:"x\u012bn k\u01d4 le",meaning:"You worked hard.",note:"A caring phrase after someone puts in effort.",category:"home"}];
const modes=[{name:"Meaning Match",promptLabel:"English",getPrompt:p=>p.meaning,getOptionTitle:p=>p.hanzi,getOptionSub:p=>p.pinyin},{name:"Phrase Match",promptLabel:"Mandarin",getPrompt:p=>p.hanzi,getOptionTitle:p=>p.meaning,getOptionSub:p=>p.pinyin},{name:"Pinyin Match",promptLabel:"Pinyin",getPrompt:p=>p.pinyin,getOptionTitle:p=>p.hanzi,getOptionSub:p=>p.meaning}];
const storageKey="kuromi-mandarin-garden-v1";
const state={currentIndex:0,round:1,modeIndex:0,activeCategory:"all",selectedAnswer:null,challenge:null,progress:loadProgress()};
const els={plants:document.querySelector("#garden-plants"),level:document.querySelector("#level-value"),leaves:document.querySelector("#leaf-value"),mastered:document.querySelector("#mastered-value"),currentHanzi:document.querySelector("#current-hanzi"),currentPinyin:document.querySelector("#current-pinyin"),currentMeaning:document.querySelector("#current-meaning"),currentNote:document.querySelector("#current-note"),prevPhrase:document.querySelector("#prev-phrase"),nextPhrase:document.querySelector("#next-phrase"),speakCurrent:document.querySelector("#speak-current"),round:document.querySelector("#round-value"),challengeTitle:document.querySelector("#challenge-title"),changeMode:document.querySelector("#change-mode"),promptLabel:document.querySelector("#prompt-label"),challengePrompt:document.querySelector("#challenge-prompt"),answerGrid:document.querySelector("#answer-grid"),feedback:document.querySelector("#feedback-text"),nextRound:document.querySelector("#next-round"),phraseList:document.querySelector("#phrase-list"),tabs:Array.from(document.querySelectorAll(".tab"))};
function loadProgress(){try{const saved=JSON.parse(localStorage.getItem(storageKey));return{leaves:Number(saved?.leaves)||0,mastered:Array.isArray(saved?.mastered)?saved.mastered:[]}}catch{return{leaves:0,mastered:[]}}}
function saveProgress(){localStorage.setItem(storageKey,JSON.stringify(state.progress))}
function renderPhrase(){const p=phrases[state.currentIndex];els.currentHanzi.textContent=p.hanzi;els.currentPinyin.textContent=p.pinyin;els.currentMeaning.textContent=p.meaning;els.currentNote.textContent=p.note}
function renderStats(){const level=Math.max(1,Math.floor(state.progress.leaves/5)+1);els.level.textContent=level;els.leaves.textContent=state.progress.leaves;els.mastered.textContent=state.progress.mastered.length;renderGarden(level)}
function renderGarden(level){const count=Math.min(18,Math.max(4,state.progress.leaves+3));els.plants.innerHTML=Array.from({length:count},(_,i)=>{const x=50+i*74%460,row=Math.floor(i/7),y=292+row*20+i%2*7,scale=.82+Math.min(level,8)*.035+i%3*.04,color=i%2?"#f38ccf":"#ffd36b",alt=i%3===0;return `<g class="plant ${i===count-1?"is-new":""}" transform="translate(${x} ${y}) scale(${scale})"><path d="M0 0 C-3 -16 -2 -28 0 -38" stroke="#d8b9ec" stroke-width="5" stroke-linecap="round" fill="none"/>${alt?`<path d="M0 -56 l7 14 16 2 -12 10 3 16 -14 -8 -14 8 3 -16 -12 -10 16 -2 Z" fill="${color}" stroke="#fff7ff" stroke-width="3"/>`:`<circle cx="0" cy="-48" r="15" fill="${color}" stroke="#fff7ff" stroke-width="4"/><circle cx="-6" cy="-51" r="3" fill="#241834"/><circle cx="6" cy="-51" r="3" fill="#241834"/><path d="M-5 -41 C-2 -38 2 -38 5 -41" fill="none" stroke="#241834" stroke-width="3" stroke-linecap="round"/>`}</g>`}).join("")}
function getFilteredPhrases(){return state.activeCategory==="all"?phrases:phrases.filter(p=>p.category===state.activeCategory)}
function renderLibrary(){els.phraseList.innerHTML=getFilteredPhrases().map(p=>`<article class="mini-card"><strong>${p.hanzi}</strong><span>${p.pinyin}</span><small>${p.meaning}${state.progress.mastered.includes(p.hanzi)?" Mastered.":""}</small></article>`).join("")}
function createChallenge(){const correct=phrases[(state.round+state.currentIndex*2)%phrases.length],options=shuffle([correct,...shuffle(phrases.filter(p=>p.hanzi!==correct.hanzi)).slice(0,3)]);state.challenge={correct,options,answered:false};state.selectedAnswer=null;state.currentIndex=phrases.findIndex(p=>p.hanzi===correct.hanzi);renderPhrase();renderChallenge()}
function renderChallenge(){const mode=modes[state.modeIndex],{correct,options}=state.challenge;els.round.textContent=state.round;els.challengeTitle.textContent="Choose the phrase";els.changeMode.textContent=mode.name;els.promptLabel.textContent=mode.promptLabel;els.challengePrompt.textContent=mode.getPrompt(correct);els.nextRound.hidden=!state.challenge.answered;els.answerGrid.innerHTML=options.map(p=>{const selected=state.selectedAnswer===p.hanzi,isCorrect=p.hanzi===correct.hanzi,result=state.challenge.answered&&selected?(isCorrect?"is-correct":"is-wrong"):"",klass=state.challenge.answered&&isCorrect?"is-correct":result;return `<button class="answer-button ${klass}" type="button" data-answer="${p.hanzi}"><strong>${mode.getOptionTitle(p)}</strong><span>${mode.getOptionSub(p)}</span></button>`}).join("")}
function chooseAnswer(hanzi){if(state.challenge.answered)return;const correct=state.challenge.correct.hanzi,ok=hanzi===correct;state.selectedAnswer=hanzi;state.challenge.answered=true;if(ok){state.progress.leaves+=1;if(!state.progress.mastered.includes(correct))state.progress.mastered.push(correct);els.feedback.textContent=`Nice. ${correct} means "${state.challenge.correct.meaning}"`}else els.feedback.textContent=`Almost. The answer is ${correct}: ${state.challenge.correct.meaning}`;saveProgress();renderStats();renderLibrary();renderChallenge()}
function nextRound(){state.round+=1;els.feedback.textContent="Pick the matching Traditional Mandarin phrase.";createChallenge()}
function shiftPhrase(delta){state.currentIndex=(state.currentIndex+delta+phrases.length)%phrases.length;renderPhrase()}
function speakCurrentPhrase(){if(!("speechSynthesis" in window)){els.feedback.textContent="Pronunciation is not available in this browser.";return}const phrase=phrases[state.currentIndex];window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(phrase.hanzi);utterance.lang="zh-TW";utterance.rate=.82;window.speechSynthesis.speak(utterance)}
function shuffle(items){return[...items].sort(()=>Math.random()-.5)}
els.prevPhrase.addEventListener("click",()=>shiftPhrase(-1));els.nextPhrase.addEventListener("click",()=>shiftPhrase(1));els.speakCurrent.addEventListener("click",speakCurrentPhrase);els.changeMode.addEventListener("click",()=>{state.modeIndex=(state.modeIndex+1)%modes.length;els.feedback.textContent="Mode changed. Try this round from a new angle.";renderChallenge()});els.nextRound.addEventListener("click",nextRound);els.answerGrid.addEventListener("click",event=>{const button=event.target.closest("[data-answer]");if(button)chooseAnswer(button.dataset.answer)});els.tabs.forEach(tab=>tab.addEventListener("click",()=>{state.activeCategory=tab.dataset.category;els.tabs.forEach(item=>item.classList.toggle("is-active",item===tab));renderLibrary()}));renderPhrase();renderStats();renderLibrary();createChallenge();
